require.config({
    baseUrl:"lib",
    paths:{
        "Bootstrap":"modules/bootstrap/js/bootstrap.min",
        "ZTree":"modules/zTree/js/jquery.ztree.all-3.5.min",
        "Date":"modules/bootstrap/plugins/datetimepicker/js/datetimepicker.min",
        "DateCN":"modules/bootstrap/plugins/datetimepicker/js/datetimepicker.cn",
        "Json2":"modules/json2/json2",
        "jquery":"modules/jquery/jquery1x.min",
        "app":"../app/"
    },
    shim:{
        "Bootstrap":["jquery"],
        "ZTree":["jquery"],
        "Json2":{}
    },
    map:{
        '*':{
            'css': 'modules/requirejs/plugin/css.min',
            'text':'modules/requirejs/plugin/text'
        }
    }
});