require.config({
    baseUrl:"./modules",
    paths:{
        "Bootstrap":"bootstrap/js/bootstrap.min",
        "zTree":"ztree/js/jquery.ztree.all-3.5.min",
        "Date":"bootstrap/plugins/datetimepicker/js/datetimepicker.min",
        "DateCN":"bootstrap/plugins/datetimepicker/js/datetimepicker.cn",
        "Json2":"json2/json2",
        "Dialog":"util/dialog",
        "jquery":"jquery/jquery1x.min",
        "app":"../app/"
    },
    shim:{
        "Bootstrap":["jquery"],
        "zTree":["jquery"],
        "Json2":{}
    },
    map:{
        '*':{
            'css': 'requirejs/plugin/css.min',
            'text':'requirejs/plugin/text'
        }
    }
});